openapi: 3.0.0
info:
  version: v1
  title: Flight Information Management System (FIMS) Authorization (Authz) Server
  description: >

    FIMS_Authz provides authorization services for FIMS stakeholders
    within UTM.  Written to the UAS Service Supplier Framework (UFAA) for
    Authentication and Authorization" at
    https://utm.arc.nasa.gov/docs/2019-UTM_Framework-NASA-TM220364.pdf

     The FIMS Authorization Server facilitates the RFC-6749 Client
        Credentials flow for UTM components that are Oauth2 Resources servers.

      # Authentication using Message Signing

      As detailed in the UFAA, the authentication method is designed to provide
        message integrity, non-repudiation, and message authentication.
        Clients authenticate by providing a JWS signature of the HTTP request body's x-www-form-urlencoded data. The signature is provided in the
        'x-utm-message-signature' HTTP header of the HTTP Request.
        As specified in the UFAA, the signature is performed using the private key
        associated with the certifcate specified by 'x5u' in the JOSE Header.

      # Scopes

        utm.nasa.gov_read.fimsadmin: Subject can read data internal to FIMS.
        utm.nasa.gov_write.fimsadmin: Subject can read, create, and update data internal to FIMS.
        utm.nasa.gov_read.operation: Subject can read operational data such as USS Instance data
        utm.nasa.gov_write.operation: Subject can read, create, and update operational data such as USS Instance data
        utm.nasa.gov_read.message: Subject can read message data such as UTM Message and Negotiations
        utm.nasa.gov_write.message: Subject can read, create, and update message data such as UTM Message and Negotiations
        utm.nasa.gov_read.publicsafety: Subject can read operations that are designated public safety operations.
        utm.nasa.gov_write.publicsafety: Subject can read, create, and update operations that are designated public safety operations.
        utm.nasa.gov_read.constraint: Subject can read UTM constraint data
        utm.nasa.gov_write.constraint: Subject can read, create, and update UTM constraint data to define areas that restrict other operations.
        utm.nasa.gov_read.conflictmanagement: Subject can read conflict management data.
        utm.nasa.gov_write.conflictmanagement: Subject can read and write conflict management data.

paths:
  /.well-known/oauth-authorization-server:
    get:
      tags:
        - A. Required Endpoints
      summary: Get API Info.  Can be used to check health.
      description: |
        Per RFC8414, this endpoint provides metadata related to use of this authorization
        server. See https://tools.ietf.org/html/rfc8414#section-3 for more details.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Metadata'

  /token:
    post:
      tags:
        - A. Required Endpoints
      summary: Request an access token.
      description: |
        The primary endpoint for this authorization server.  Used to request an access token
        suitbable for authorizing data exchanges within the USS Network.

        Implemented per https://tools.ietf.org/html/rfc6749#section-3.2 .
      security:
      - fims-jws: []
      requestBody:
        description: Data supplied by the client for a token request.
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - grant_type
                - client_id
                - scope
                - timestamp
              additionalProperties: false
              properties:
                grant_type:
                  type: string
                  enum:
                    - client_credentials
                client_id:
                  description: the client_id (uss_name) of the reqeusting USS.
                  type: string
                scope:
                  description: |
                    The requested scope.
                  type: string
                current_timestamp:
                  description: |
                    A timestamp of the current time generated by the client at request
                    generation time.  NOTE: should be made to align with UTM commons
                    definition of a timestamp (i.e. UTC only, millisecond precision).

                    May be used by the authorization server to validate the request.
                  type: string
                  format: date-time
                salt:
                  description: |
                    Additional length and randomization added to the request since this
                    HTTP body is also JWS body.

                    NOTE1: should be made to align with UTM commons definition of a
                    UUID (i.e. v4 and therefore matching regex).

                    NOTE2: This is a suggested/experimental field at the moment. Needs
                    discussion.
                  type: string
                  format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
servers:
  - url: 'https://ansp-authority-baseurl/oauth/{info.version}'

components:
  securitySchemes:
    fims-jws:
      description: |
        FIMS-Authz uses a JWS-based approach to authentication.

        USS clients are vetted/qualified in advance and provide an owned DNS
        name that serves as their primary identifer.  That DNS name is then
        included in a certificate (as a subject alternative name) that the
        client procures from an approved CA.  The private key related to that
        public certificate is then used to create a JWS by signing the HTTP
        body of the token request.

        The JWS is provided in a "Detached Content" manner, with just
        the JWS header and JWS signature fields provided in the HTTP
        header.  The HTTP body can be used to reconstruct a full JWS.

        See RFC7515 for more information on the detached content approach:
        https://tools.ietf.org/html/rfc7515#appendix-F

        Details are provided in:
        https://utm.arc.nasa.gov/docs/2019-UTM_Framework-NASA-TM220364.pdf

      type: apiKey
      in: header
      name: x-utm-message-signature

  schemas:
    TokenResponse:
      type: object
      additionalProperties: false
      properties:
        access_token:
          type: string
          format: JwsCompactSerialization
          description: see definitions/JwsCompactSerialization in this spec
        scope:
          type: string
          description: white space separated list of scopes
        token_type:
          type: string
          enum:
            - bearer
        expires_in:
          type: number
          format: integer
          description: see definitions/JwtClaimsSet.exp property in this spec
        sub:
          type: string
          description: see definitions/JwtClaimsSet in this spec
        jti:
          type: string
          format: uuid
          description: see definitions/JwtClaimsSet in this spec
        iss:
          type: string
          description: see definitions/JwtClaimsSet in this spec
        nbf:
          type: number
          description: see definitions/JwtClaimsSet in this spec
      example:
        access_token: tokenstring
        token_type: bearer
        expires_in: 3599
        scope: utm.nasa.gov_write.operation
        sub: nuss1.testing.nasa.gov
        nbf: 1509470774
        iss: fims.arc.nasa.gov/fimsAuthServer
        jti: 4d4c1a63-0959-48cc-885a-3648fd582db7
    JwsCompactSerialization:
      description: >-
        The token provided by the FIMS Authorization Server is a JWS
        representing a JWT.  The token is actually a JWS Compact Serialization
        string as described in RFC 7515.  For clarity of documentation, we
        represent the pre-serialized components here as a JSON schema.
      type: object
      additionalProperties: false
      properties:
        jose_header:
          $ref: '#/components/schemas/JoseHeader'
        jws_payload:
          $ref: '#/components/schemas/JwtClaimsSet'
        jws_signature:
          type: string
          description: See RFC 7515 for details.
    JoseHeader:
      type: object
      properties:
        alg:
          type: string
        typ:
          type: string
          enum:
            - JWT
          description: >-
            The FIMS Authorization Server only support 'JWT' (JSON Web Token) as
            the algorithm type.
    TokenKeyResponse:
      type: object
      additionalProperties: false
      properties:
        alg:
          type: string
          description: >-
            A designator for the algorithm used to sign the key.  Values defined
            by a Java specfication from Oracle
            (http://docs.oracle.com/javase/8/docs/technotes/guides/security/StandardNames.html).
        value:
          type: string
          description: >-
            A key signed by the algorithm noted in 'alg' property.  The key is
            preceded by '-----BEGIN PUBLIC KEY-----\n' without the single quotes
            and appended with '\n-----END PUBLIC KEY-----' without the single
            quotes.
    JwtClaimsSet:
      type: object
      required:
        - iss
        - sub
        - exp
        - nbf
        - iat
        - jti
        - scope
      additionalProperties: false
      description: Claims included within access tokens provided by this authorization server.
      properties:
        iss:
          type: string
          format: URL
          description: >-
            The "iss" (issuer) claim identifies the principal that issued the
            JWT. The URL of the FIMS Authorization Server.
        sub:
          type: string
          description: >-
            The "sub" (suv4-draft identifies the principal that is the subject
            of the JWT.
        exp:
          type: integer
          format: unix-time
          description: >-
            The "exp" (expiration time) claim identifies the expiration time on
            or after which the JWT MUST NOT be accepted for processing.  The
            processing of the "exp" claim requires that the current date/time
            MUST be before the expiration date/time listed in the "exp" claim.
        nbf:
          type: integer
          format: unix-time
          description: >-
            The "nbf" (not before) claim identifies the time before which the
            JWT MUST NOT be accepted for processing.  The processing of the
            "nbf" claim requires that the current date/time MUST be after or
            equal to the not-before date/time listed in the "nbf" claim.
        iat:
          type: integer
          format: unix-time
          description: >-
            The "iat" (issued at) claim identifies the time at which the JWT was
            issued.  This claim can be used to determine the age of the JWT.
        jti:
          type: string
          format: uuid
          description: >-
            The "jti" (JWT ID) claim provides a unique identifier for the JWT.
            For this server, this is satisfied by the use of a UUID.
        scope:
          description: See securityDefinitions section in this spec.
          type: string
    Metadata:
      type: object
      description: Information provided at the `/.well-known/oauth-authorization-server` endpoint.
      required:
        - issuer
        - token_endpoint
        - jwks_uri
        - scopes_supported
        - response_types_supported
        - grant_types_supported
        - token_endpoint_auth_methods_supported
        - token_endpoint_auth_signing_alg_values_supported
        - service_documentation
        - jwt_claims
        - signed_metadata
      additionalProperties: false
      properties:
        issuer:
          type: string
          format: url
          description: >-
            The authorization server's issuer identifier, which is a URL that
            uses the "https" scheme and has no query or fragment components.
            This is the location where ".well-known" RFC 8615 resources
            containing information about the authorization server are
            published.  Using these well-known resources is described in Section
            3.  The issuer identifier is used to prevent authorization server
            mix-up attacks, as described in "OAuth 2.0 Mix-Up Mitigation".
        token_endpoint:
          type: string
          format: url
          description: >-
            URL of the authorization server's token endpoint [RFC6749].  This is
            REQUIRED unless only the implicit grant type is used.
        jwks_uri:
          type: string 
          format: uri 
          description: |
            URL of the authorization server's JWK Set
            document.  The referenced document contains the signing key(s) the
            client uses to validate signatures from the authorization server.
            This URL MUST use the "https" scheme.  The JWK Set MAY also
            contain the server's encryption key or keys, which are used by
            clients to encrypt requests to the server.  When both signing and
            encryption keys are made available, a "use" (public key use)
            parameter value is REQUIRED for all keys in the referenced JWK Set
            to indicate each key's intended usage.
        scopes_supported:
          type: array
          items:
            type: string
          description: >-
            JSON array containing a list of the OAuth 2.0 [RFC6749] "scope"
            values that this authorization server supports. Servers MAY choose
            not to advertise some supported scope values even when this
            parameter is used.
        response_types_supported:
          type: array
          items:
            type: string
            enum: [none]
          minItems: 0
          maxItems: 0
          description: >-
            JSON array containing a list of the OAuth 2.0 "response_type" values
            that this authorization server supports. These values are required
            for responses from calls to the authorization endpoint, thus this
            array may be empty if no grant flows use the authorization endpoint,
            thus this server returns an empty array. (definitions in RFC 7591)

            This field is required per RFC 8414, but this auth server does not
            support the flows that use this field, thus an empty array is returned.
        grant_types_supported:
          type: array
          items:
            type: string
            enum: [client_credentials]
          minItems: 1
          maxItems: 1
          description: >-
            JSON array containing a list of the OAuth 2.0 grant type values that
            this authorization server supports. (definitions in RFC 7591)
        token_endpoint_auth_methods_supported:
          type: array
          items:
            type: string
            enum: [private_key_jwt]
          minItems: 1
          maxItems: 1
          description: >-
            JSON array containing a list of client authentication methods
            supported by this token endpoint.  Client authentication method
            values are used in the "token_endpoint_auth_method" parameter
            defined in Section 2 of [RFC7591].  If omitted, the default is
            "client_secret_basic" -- the HTTP Basic Authentication Scheme
            specified in Section 2.3.1 of OAuth 2.0 [RFC6749]. FIMS-Authz will
            only support private_key_jwt.
        token_endpoint_auth_signing_alg_values_supported:
          type: array
          items:
            type: string
            enum: [HS256, RS256, ES256]
          minItems: 3
          maxItems: 3
          uniqueItems: true 
          description: |-
            JSON array containing a list of the JWS signing algorithms (alg
            values) supported by the token endpoint for the signature on the JWT
            [JWT] used to authenticate the client at the token endpoint for the
            `private_key_jwt` and `client_secret_jwt` authentication methods.
            Servers SHOULD support "RS256". The value "none" MUST NOT be used.

            See UFAA doc for details.
        service_documentation:
          type: string
          format: url
          description: >-
            URL of a page containing human-readable information that developers
            might want or need to know when using the authorization server.  In
            particular, if the authorization server does not support Dynamic
            Client Registration, then information on how to register clients
            needs to be provided in this documentation.
        jwt_claims:
          $ref: '#/components/schemas/JwtClaimsSet'
        signed_metadata:
          type: string 
          format: JWT 
          description: |
            A JWT containing metadata values about the authorization server as
            claims.  This is a string value consisting of the entire signed
            JWT.  A "signed_metadata" metadata value SHOULD NOT appear as a
            claim in the JWT.

