swagger: '2.0'
info:
  title: Performance Authorization
  description: >-
    The following definition is from:

    FAA NextGen UTM Concept of Operations v1.0

    https://utm.arc.nasa.gov/docs/2018-UTM-ConOps-v1.0.pdf

    NOTE: THIS IS A CONCEPTUAL DEFINITION. IT IS NOT CURRENT POLICY NOR A CURRENT RULE.

    'All BVLOS Operators are required to obtain a Performance Authorization from the FAA prior to
    conducting a UTM operation. A Performance Authorization is a FAA regulatory approval for BVLOS
    Operators to perform a specific type of operation in a specified geographical area. The FAA grants a
    Performance Authorization when a UAS Operator’s proposed ground and air assets are sufficient to
    meet an established level of performance in the airspace in which they intend to operate.'
  version: 'v1'
  contact:
    name: 'NASA Ames Research Center, Aviation Systems Division'
    url: 'https://utm.arc.nasa.gov/'
    email: joseph.rios@nasa.gov
  license:
    name: NASA Open Source Agreement
    url: 'https://ti.arc.nasa.gov/opensource/nosa/'

paths:
  '/no-paths':
    put:
      responses:
        '410':
          description: >-
            Gone. Not implemented. Will not be implemented. Path included for
            proper use by automated tooling.  Tools sometimes do not like
            when there are no paths, but domains do not contain paths.

definitions:
  PerformanceAuthorization:
    type: object
    required:
      - performance_authorization_id
      - state
      - contacts
    properties:
      performance_authorization_id:
        description: >-
          A universally unique identifier for this performance authorization.
        $ref: '#/definitions/PerformanceAuthorizationUUID'
      state:
        description: >-
          The current state of this Performance Authorization.
        type: string
        enum:
          - DEVELOPMENT
          - APPLICATION
          - REVIEW
          - APPROVED
          - REJECTED
      organization:
        $ref: 'https://raw.githubusercontent.com/nasa/utm-apis/v4-draft/utm-domains/utm-domain-commons.yaml#/definitions/PersonOrOrganization'
      contacts:
        description: >-
          List of individual(s) at the applying serving as primary contacts for
          this performance authorization.
        type: array
        minItems: 1
        maxItems: 5
        items:
          $ref: 'https://raw.githubusercontent.com/nasa/utm-apis/v4-draft/utm-domains/utm-domain-commons.yaml#/definitions/PersonOrOrganization'
      operation_types:
        description: >-
          asdf
        type: array
        items:
          $ref: '#/definitions/OperationType'


  EquipmentSpecification:
    type: object
    properties:
      equipment_specifiation_label:
        $ref: '#/definitions/PerformanceAuthorizationLabel'
      flight_crew_comm_freq:
        description: >-
          add descp.  MHz?  Fix bounds.
        type: number
        format: double
        minimum: 0.0
        maximum: 30000.0

  MissionCharacteristics:
    type: object
    properties:
      
  AreaOfOperation:
    type: object
    properties:

  StandardProvisions:
    type: object
    properties:

  SpecialProvisions:
    type: object
    properties:

  OperationType:
    type: object
    properties:
      base_operating_rule:
        type: string
        enum:
          - 107
          - 107X
      operation_type_label:
        description: >-
          A label to indicate this operation type within this performance
          authorization.  Must be distinct from all other operation type
          labels within this performance authorization.
        $ref: '#/definitions/PerformanceAuthorizationLabel'
      equipment_specification_reference:
        description: >-
          A reference to the equipment specification to be associated with this
          operation type.
        $ref: '#/definitions/PerformanceAuthorizationLabel'
      mission_characteristics_reference:
        description: >-
          A reference to the mission characteristics to be associated with this
          operation type.
        $ref: '#/definitions/PerformanceAuthorizationLabel'
      area_of_operation_references:
        description: >-
          A reference to the area of operations to be associated with this
          operation type.
        type: array
        minItems: 1
        maxItems: 100
        items:
          $ref: '#/definitions/PerformanceAuthorizationLabel'
      standard_provisions_reference:
        description: >-
          A reference to the standard provisions to be associated with this
          operation type.
        $ref: '#/definitions/PerformanceAuthorizationLabel'
      special_provisions_reference:
        description: >-
          A reference to the special provisions to be associated with this
          operation type.
        $ref: '#/definitions/PerformanceAuthorizationLabel'

  PerformanceAuthorizationLabel:
    description: >-
      A reusable field describing a label with a performance authorization.  Used
      by the various components of the performance authorization to efficiently
      reference each other as needed.
    type: string
    minLength: 1
    maxLength: 30
  PerformanceAuthorizationUUID:
    type: string
    format: uuid
    pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    example: 'd7126818-d280-475f-aaee-c16e9c6f04e0'
    maxLength: 36
    minLength: 36
