---
swagger: "2.0"
info:
  version: "v4"
  title: "NUSS UAS Operator API's v4 endpoints"
  description: "Additional endpoints."

host: "some.host"
basePath: "/operator"
schemes:
- "https"
paths:

  /lun-messages:
    get:
      summary: |
        Get messages related to other operations in the LUN.
      description: >
        This endpoint will return messages related to operations that are not
        managed by NUSS.  Specifically it will return messages for operations
        managed by other USSs that are in the same LUN as the client's operation.
      produces:
      - "application/json"
      parameters:
      - name: "sort"
        in: "query"
        description: "sort"
        required: false
        type: "string"
      - name: "limit"
        in: "query"
        description: "limit"
        required: false
        type: "integer"
        default: 10
        format: "int32"
      - name: "offset"
        in: "query"
        description: "offset"
        required: false
        type: "integer"
        format: "int32"
      - name: "sent_time_before"
        in: "query"
        description: "Returns Message with sent_time before or equal to the given time"
        required: false
        type: string
        format: date-time
        minLength: 25
        maxLength: 25
      - name: "sent_time_after"
        in: "query"
        description: "Returns Messages with sent_time after or equal to the given time"
        required: false
        type: string
        format: date-time
        minLength: 25
        maxLength: 25
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: >-
                https://raw.githubusercontent.com/nasa/utm-apis/v4-draft/utm-domains/utm-domain-commons.yaml#/definitions/UTMMessage
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
  /lun-operations:
    get:
      summary: |
        Get other operations in LUN.
      description: >
        This endpoint will return operations that are not
        managed by NUSS.
      produces:
      - "application/json"
      parameters:
      - name: "state"
        in: "query"
        description: "You can specify ASC and DESC (or asc/desc) as follows: https://host.nasa.gov/nuss/operator/messages?sort=DESC

          You can also specify limit and offset.

          Returns Operations with an OR list given states. Eg. state=A,V
           returns operations in A or V states. Cannot use with state_not_eq."
        required: false
        type: array
        minItems: 1
        maxItems: 13
        items:
          type: "string"
          minLength: 5
          maxLength: 14
      - name: "state_not_eq"
        in: "query"
        description: "Returns Operations with other than the given states. Eg state_not_eq=X,C. Cannot use with state."
        required: false
        type: array
        minItems: 1
        maxItems: 13
        items:
          type: "string"
          minLength: 5
          maxLength: 14
      - name: "effective_time_begin_before"
        in: "query"
        description: "Returns Operations with effective_begin_time before or equal to the given time"
        required: false
        type: string
        format: date-time
        minLength: 25
        maxLength: 25
      - name: "effective_time_begin_after"
        in: "query"
        description: "Returns Operations with effective_begin_time after or equal to the given time"
        required: false
        type: string
        format: date-time
        minLength: 25
        maxLength: 25
      - name: "effective_time_end_before"
        in: "query"
        description: "Returns Operations with effective_end_time before or equal to the given time"
        required: false
        type: string
        format: date-time
        minLength: 25
        maxLength: 25
      - name: "effective_time_end_after"
        in: "query"
        description: "Returns Operations with effective_end_time after or equal to the given time"
        required: false
        type: string
        format: date-time
        minLength: 25
        maxLength: 25
      - name: "inside_bbox"
        in: "query"
        description: "Returns Operations with flight geographies inside or intersecting the bbox.
          The coordinates are comma delimited (lon_min,lat_min,lon_max,lat_max). Example: -121.1133,36.5317,-121.0941,36.6530"
        required: false
        type: array
        maxItems: 4
        minItems: 4
        items:
          type: number
          format: double
      - name: "sort"
        in: "query"
        description: "sorts the results by submit_time. Valid values - asc, desc. Default value is desc."
        required: false
        type: "string"
        minLength: 3
        maxLength: 4
      - name: "limit"
        in: "query"
        description: "limit"
        required: false
        type: "integer"
        default: 10
        format: "int32"
      - name: "offset"
        in: "query"
        description: "offset"
        required: false
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: >-
                https://raw.githubusercontent.com/nasa/utm-apis/v4-draft/utm-domains/utm-domain-commons.yaml#/definitions/Operation
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
  /lun-positions:
    get:
      summary: |
        Get positions in LUN.
      description: >
        This endpoint will return positions associated with operations that are not
        managed by NUSS.
      produces:
      - "application/json"
      parameters:
      - name: "sort"
        in: "query"
        description: "sort"
        required: false
        type: "string"
      - name: "limit"
        in: "query"
        description: "limit"
        required: false
        type: "integer"
        default: 10
        format: "int32"
      - name: "offset"
        in: "query"
        description: "offset"
        required: false
        type: "integer"
        format: "int32"
      - name: "sent_time_before"
        in: "query"
        description: "Returns Message with sent_time before or equal to the given time"
        required: false
        type: string
        format: date-time
        minLength: 25
        maxLength: 25
      - name: "sent_time_after"
        in: "query"
        description: "Returns Messages with sent_time after or equal to the given time"
        required: false
        type: string
        format: date-time
        minLength: 25
        maxLength: 25
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: >-
                https://raw.githubusercontent.com/nasa/utm-apis/v4-draft/utm-domains/utm-domain-commons.yaml#/definitions/Position
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
